In [3]:
import torch
print(torch.__version__)

2.5.1+cu124


In [8]:
if torch.cuda.is_available():
  print("GPU Available")
  print(f"using GPU :{torch.cuda.get_device_name(0)}")
else :
  print("GPU not available, Using CPU")

GPU Available
using GPU :Tesla T4


# Creating Tensors

In [11]:
# using empty
a=torch.empty(2,3)

In [12]:
torch.empty(4,3)

tensor([[2.8243e-34, 0.0000e+00, 3.4872e-07],
        [4.5193e-41, 1.4013e-45, 0.0000e+00],
        [7.0065e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [13]:
# Check type
type(a)

torch.Tensor

In [16]:
# using Zeros

torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [18]:
# using ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
# using rand

torch.rand(2,4)

tensor([[0.0322, 0.1557, 0.9632, 0.5473],
        [0.5361, 0.6603, 0.5529, 0.0741]])

In [24]:
# using seed

torch.rand(2,4)

tensor([[0.5717, 0.4048, 0.9325, 0.0606],
        [0.4629, 0.4854, 0.6043, 0.6521]])

In [26]:
torch.manual_seed(50)

torch.rand(2,4)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877]])

In [27]:
torch.manual_seed(50)

torch.rand(2,4)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877]])

In [33]:
# Using Tensor

torch.tensor([[1,2,3,4],[5,6,7,8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [35]:
# Using arange
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
torch.arange(0,100,10).reshape(2,5)

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [44]:
torch.arange(0,100,10).reshape(2,5)[:,2:]

tensor([[20, 30, 40],
        [70, 80, 90]])

In [46]:
# Using linspace

torch.linspace(0,100,20)

tensor([  0.0000,   5.2632,  10.5263,  15.7895,  21.0526,  26.3158,  31.5789,
         36.8421,  42.1053,  47.3684,  52.6316,  57.8947,  63.1579,  68.4211,
         73.6842,  78.9474,  84.2105,  89.4737,  94.7368, 100.0000])

In [50]:
# using eye(Identity)

torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [52]:
# using full
torch.full((2,3),5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [54]:
torch.full((2,3),13)

tensor([[13, 13, 13],
        [13, 13, 13]])

# tensor shape

In [55]:
x=torch.tensor([[1,3,5],[2,4,6]])

In [56]:
x.shape

torch.Size([2, 3])

In [60]:
torch.empty_like(x)

tensor([[       10759048,        10759048, 138517407309552],
        [138517407309600,             128,              48]])

In [61]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [63]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [64]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'