In [1]:
import torch
print(torch.__version__)

2.6.0+cu118


In [2]:
if torch.cuda.is_available():
  print("GPU Available")
  print(f"using GPU :{torch.cuda.get_device_name(0)}")
else :
  print("GPU not available, Using CPU")

GPU Available
using GPU :NVIDIA GeForce RTX 2050


# Creating Tensors

In [3]:
# using empty
a=torch.empty(2,3)

In [4]:
torch.empty(4,3)

tensor([[5.0594e+07, 1.6802e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
# Check type
type(a)

torch.Tensor

In [6]:
# using Zeros

torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [8]:
# using ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand

torch.rand(2,4)

tensor([[0.5833, 0.8458, 0.7708, 0.6886],
        [0.7789, 0.4917, 0.1462, 0.7892]])

In [10]:
# using seed

torch.rand(2,4)

tensor([[0.8376, 0.3796, 0.3701, 0.7487],
        [0.6002, 0.8644, 0.5620, 0.9053]])

In [11]:
torch.manual_seed(50)

torch.rand(2,4)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877]])

In [12]:
torch.manual_seed(50)

torch.rand(2,4)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877]])

In [13]:
# Using Tensor

torch.tensor([[1,2,3,4],[5,6,7,8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [14]:
# Using arange
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
torch.arange(0,100,10).reshape(2,5)

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [16]:
torch.arange(0,100,10).reshape(2,5)[:,2:]

tensor([[20, 30, 40],
        [70, 80, 90]])

In [17]:
# Using linspace

torch.linspace(0,100,20)

tensor([  0.0000,   5.2632,  10.5263,  15.7895,  21.0526,  26.3158,  31.5789,
         36.8421,  42.1053,  47.3684,  52.6316,  57.8947,  63.1579,  68.4211,
         73.6842,  78.9474,  84.2105,  89.4737,  94.7368, 100.0000])

In [18]:
# using eye(Identity)

torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [19]:
# using full
torch.full((2,3),5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [20]:
torch.full((2,3),13)

tensor([[13, 13, 13],
        [13, 13, 13]])

# tensor shape

In [21]:
x=torch.tensor([[1,3,5],[2,4,6]])

In [22]:
x.shape

torch.Size([2, 3])

In [23]:
torch.empty_like(x)

tensor([[5150945117616,             0,             0],
        [            0,             0,             0]])

In [24]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.7413, 0.9840, 0.9879],
        [0.8389, 0.5791, 0.8991]], dtype=torch.float64)

# Tensor Datatypes

In [27]:
# find data type
x.dtype


torch.int64

In [28]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [29]:
torch.tensor([1,2,3,4],dtype=torch.float64)

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [30]:
# using to()
x.to(torch.float64)

tensor([[1., 3., 5.],
        [2., 4., 6.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical operations

## Scalar operations

In [31]:
x=torch.rand(2,3)
x

tensor([[0.7145, 0.5058, 0.0518],
        [0.2492, 0.2395, 0.4233]])

In [32]:
# addition
x+2

tensor([[2.7145, 2.5058, 2.0518],
        [2.2492, 2.2395, 2.4233]])

In [33]:
x+x

tensor([[1.4291, 1.0117, 0.1036],
        [0.4983, 0.4790, 0.8466]])

In [34]:
# Subtraction

x-2

tensor([[-1.2855, -1.4942, -1.9482],
        [-1.7508, -1.7605, -1.5767]])

In [35]:
# multiplication
x* 10

tensor([[7.1455, 5.0585, 0.5179],
        [2.4915, 2.3951, 4.2329]])

In [36]:
# Division
x/2

tensor([[0.3573, 0.2529, 0.0259],
        [0.1246, 0.1198, 0.2116]])

In [37]:
# int division
(x*100)//2

tensor([[35., 25.,  2.],
        [12., 11., 21.]])

In [38]:
# mod
((x*100)//2)%2

tensor([[1., 1., 0.],
        [0., 1., 1.]])

In [39]:
# power
x**2

tensor([[0.5106, 0.2559, 0.0027],
        [0.0621, 0.0574, 0.1792]])

# Element wise operation

In [40]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [41]:
a

tensor([[0.0022, 0.6848, 0.7497],
        [0.2489, 0.3490, 0.1953]])

In [42]:
b

tensor([[0.2792, 0.2526, 0.3792],
        [0.7686, 0.6907, 0.7526]])

In [43]:
# add
a+b

tensor([[0.2814, 0.9374, 1.1289],
        [1.0175, 1.0397, 0.9479]])

In [44]:
# div
a-b

tensor([[-0.2771,  0.4322,  0.3705],
        [-0.5197, -0.3417, -0.5574]])

In [45]:
#mul
a*b

tensor([[0.0006, 0.1730, 0.2843],
        [0.1913, 0.2411, 0.1470]])

In [46]:
# div
a/b

tensor([[0.0077, 2.7112, 1.9769],
        [0.3238, 0.5053, 0.2594]])

In [47]:
# Power
a**b

tensor([[0.1802, 0.9088, 0.8965],
        [0.3434, 0.4833, 0.2925]])

In [48]:
# Mode
a%b

tensor([[0.0022, 0.1796, 0.3705],
        [0.2489, 0.3490, 0.1953]])

In [49]:
c=torch.tensor([-2,3,-3,-5,4,5])

In [50]:
# abs
torch.abs(c)

tensor([2, 3, 3, 5, 4, 5])

In [51]:
# negative
torch.negative(c)

tensor([ 2, -3,  3,  5, -4, -5])

In [52]:
d=torch.linspace(1,4,3)
d

tensor([1.0000, 2.5000, 4.0000])

In [53]:
# round
torch.round(d)


tensor([1., 2., 4.])

In [54]:
#  ceil
torch.ceil(d)

tensor([1., 3., 4.])

In [55]:
# floor
torch.floor(d)

tensor([1., 2., 4.])

In [56]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.5000, 3.0000])

# Reduction operation.


In [57]:
r=torch.randint(size=(2,3),low=0,high=10)

In [58]:
r

tensor([[8, 3, 0],
        [1, 5, 9]])

In [59]:
# sum
torch.sum(r)

tensor(26)

In [60]:
# sum along columns
torch.sum(r,dim=0)

tensor([9, 8, 9])

In [61]:
# sum along rows
torch.sum(r,dim=1)

tensor([11, 15])

In [62]:
# mean
torch.mean(r.float())

tensor(4.3333)

In [63]:
# mean along column
torch.mean(r.float(),dim=0)

tensor([4.5000, 4.0000, 4.5000])

In [64]:
# mean along rows
torch.mean(r.float(),dim=1)

tensor([3.6667, 5.0000])

In [65]:
# Median
torch.median(r.float())

tensor(3.)

In [66]:
# max
torch.max(r)

tensor(9)

In [67]:
# min
torch.min(r)

tensor(0)

In [68]:
# product
torch.prod(r)

tensor(0)

In [69]:
# std
torch.std(r.float())

tensor(3.6697)

In [70]:
# variance
torch.var(r.float())

tensor(13.4667)

In [71]:
# argmax(for finding the position of largest item)

In [72]:
torch.argmax(r)

tensor(5)

In [73]:
# argmin
torch.argmin(r)

tensor(2)

# Matrix operations

In [74]:
p=torch.randint(size=(2,3),low=0,high=10)
q=torch.randint(size=(3,2),low=0,high=10)
print(p)
print(q)

tensor([[8, 4, 9],
        [4, 2, 8]])
tensor([[7, 0],
        [6, 2],
        [2, 1]])


In [75]:
# matrix mul
torch.matmul(p,q)

tensor([[98, 17],
        [56, 12]])

In [76]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])
vector1,vector2

(tensor([1, 2]), tensor([3, 4]))

In [77]:
#dot product
torch.dot(vector1,vector2)

tensor(11)

In [78]:
# transpose
t=torch.randint(size=(3,3),low=0,high=10)
t

tensor([[8, 3, 1],
        [6, 4, 1],
        [0, 0, 9]])

In [79]:
torch.transpose(t,0,1)

tensor([[8, 6, 0],
        [3, 4, 0],
        [1, 1, 9]])

In [80]:
# determinant
torch.det(t.float())

tensor(126.)

In [81]:
# inverse
torch.inverse(t.float())

tensor([[ 0.2857, -0.2143, -0.0079],
        [-0.4286,  0.5714, -0.0159],
        [ 0.0000,  0.0000,  0.1111]])

# Comparisons

In [82]:
m=torch.randint(size=(2,3),low=0,high=10)
n=torch.randint(size=(2,3),low=0,high=10)
print(m)
print(n)

tensor([[9, 6, 2],
        [3, 8, 2]])
tensor([[3, 9, 2],
        [6, 8, 8]])


In [83]:
# greater than
m>n

tensor([[ True, False, False],
        [False, False, False]])

In [84]:
# less than

In [85]:
m<n

tensor([[False,  True, False],
        [ True, False,  True]])

In [86]:
# equal to

In [87]:
m==n

tensor([[False, False,  True],
        [False,  True, False]])

In [88]:
# not equal to
m!=n

tensor([[ True,  True, False],
        [ True, False,  True]])

In [89]:
# Greater than or eqaul to
m>=n

tensor([[ True, False,  True],
        [False,  True, False]])

# Special functins

In [90]:
s=torch.randint(size=(2,3),low=1,high=10)
s

tensor([[8, 7, 8],
        [9, 7, 3]])

In [91]:
# log
torch.log(s)

tensor([[2.0794, 1.9459, 2.0794],
        [2.1972, 1.9459, 1.0986]])

In [92]:
# exp
torch.exp(s)

tensor([[2980.9580, 1096.6332, 2980.9580],
        [8103.0840, 1096.6332,   20.0855]])

In [93]:
# sqrt
torch.sqrt(s)

tensor([[2.8284, 2.6458, 2.8284],
        [3.0000, 2.6458, 1.7321]])

In [94]:
# sigmoid
torch.sigmoid(s.float())

tensor([[0.9997, 0.9991, 0.9997],
        [0.9999, 0.9991, 0.9526]])

In [95]:
# softmax
torch.softmax(s.float(),dim=0)

tensor([[0.2689, 0.5000, 0.9933],
        [0.7311, 0.5000, 0.0067]])

In [96]:
# relu
torch.relu(s.float())

tensor([[8., 7., 8.],
        [9., 7., 3.]])

# Inplace operations

In [97]:
s=torch.randint(size=(2,3),low=1,high=10)
t=torch.randint(size=(2,3),low=1,high=10)
print(s)
print(t)

tensor([[2, 6, 5],
        [3, 4, 8]])
tensor([[4, 5, 3],
        [8, 7, 3]])


In [98]:
s+t

tensor([[ 6, 11,  8],
        [11, 11, 11]])

In [99]:
s.add_(t)

tensor([[ 6, 11,  8],
        [11, 11, 11]])

In [100]:
s

tensor([[ 6, 11,  8],
        [11, 11, 11]])

In [101]:
torch.relu(s)

tensor([[ 6, 11,  8],
        [11, 11, 11]])

In [102]:
s.relu_()

tensor([[ 6, 11,  8],
        [11, 11, 11]])

In [103]:
s

tensor([[ 6, 11,  8],
        [11, 11, 11]])

In [104]:
torch.relu_(s)

tensor([[ 6, 11,  8],
        [11, 11, 11]])

# Copying a tensor

In [105]:
from re import U
u=torch.rand(2,2)
u

tensor([[0.3192, 0.5750],
        [0.1538, 0.2540]])

In [106]:
v=u

In [107]:
v

tensor([[0.3192, 0.5750],
        [0.1538, 0.2540]])

In [108]:
u[0][0]=0

In [109]:
u,v

(tensor([[0.0000, 0.5750],
         [0.1538, 0.2540]]),
 tensor([[0.0000, 0.5750],
         [0.1538, 0.2540]]))

In [110]:
id(u)

2236531711008

In [111]:
id(v)

2236531711008

In [112]:
# clone
v=u.clone()

In [113]:
v

tensor([[0.0000, 0.5750],
        [0.1538, 0.2540]])

In [114]:
u[0][1]=1

In [115]:
u,v

(tensor([[0.0000, 1.0000],
         [0.1538, 0.2540]]),
 tensor([[0.0000, 0.5750],
         [0.1538, 0.2540]]))

# Tensor operation on GPU

In [116]:
torch.cuda.is_available()

True

In [117]:
device=torch.device('cuda')

In [118]:
# Creating new tensor on Gpu
torch.rand( (2,3),device=device)

tensor([[0.3146, 0.1458, 0.3482],
        [0.9447, 0.1015, 0.8101]], device='cuda:0')

In [119]:
# moving an existing tensor to GPU

In [120]:
a

tensor([[0.0022, 0.6848, 0.7497],
        [0.2489, 0.3490, 0.1953]])

In [121]:
G=a.to(device=device)
G


tensor([[0.0022, 0.6848, 0.7497],
        [0.2489, 0.3490, 0.1953]], device='cuda:0')

# Performance comparison : CPU & GPU


In [122]:
import time

In [123]:
# Define matrix size
size=10000

In [124]:
mat_cpu1=torch.randn(size,size)
mat_cpu2=torch.randn(size,size)

In [125]:
# measures the time
start=time.time()
res_cpu=torch.matmul(mat_cpu1,mat_cpu2)
cpu_time=time.time()-start

print(f"time taken in Cpu is {cpu_time}")




time taken in Cpu is 9.549392223358154


In [126]:
# Moving arix to gpu
mat_gpu1=mat_cpu1.to('cuda')
mat_gpu2=mat_cpu2.to('cuda')


# measure time

start=time.time()
res_gpu=torch.matmul(mat_gpu1,mat_gpu2)
gpu_time=time.time()-start
torch.cuda.synchronize()

print(f"time taken in Cpu is {gpu_time}")

time taken in Cpu is 0.24860048294067383


 # reshaping tensors

In [127]:

a=torch.ones((4,4))
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [128]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [129]:
# Flatten
a.flatten()


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [130]:
b=torch.rand(2,3,4)
b

tensor([[[0.7455, 0.5947, 0.5939, 0.4995],
         [0.3332, 0.6272, 0.9073, 0.4899],
         [0.6020, 0.1876, 0.9578, 0.7122]],

        [[0.2956, 0.9522, 0.7329, 0.2334],
         [0.7504, 0.0606, 0.4756, 0.5282],
         [0.0718, 0.7238, 0.0195, 0.0807]]])

In [131]:
# permute
b.permute(2,0,1)

tensor([[[0.7455, 0.3332, 0.6020],
         [0.2956, 0.7504, 0.0718]],

        [[0.5947, 0.6272, 0.1876],
         [0.9522, 0.0606, 0.7238]],

        [[0.5939, 0.9073, 0.9578],
         [0.7329, 0.4756, 0.0195]],

        [[0.4995, 0.4899, 0.7122],
         [0.2334, 0.5282, 0.0807]]])

In [132]:
# unsqueeze
# image size
c=torch.rand(size=(226,226,3))
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [133]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0).shape


torch.Size([20])

# Moving tensors between Numpy and Pytoch

In [134]:
import numpy as np

In [135]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [136]:
b=a.numpy()
b

array([1, 2, 3], dtype=int64)

In [137]:
type(b)

numpy.ndarray

In [138]:
c=np.array([5,6,7])
c

array([5, 6, 7])

In [139]:
d=torch.from_numpy(c)

In [140]:
type(d)

torch.Tensor