# Simple neural network

In [16]:
# Create model class

import torch 
import torch.nn as nn


class Model(nn.Module):

    def __init__(self,num_faetures):

        super().__init__()
        self.linear=nn.Linear(num_faetures,1)
        self.sigmoid=nn.Sigmoid()
    

    def forward(self,features):

        out=self.linear(features)
        out=self.sigmoid(out)

        return out
    
    



In [17]:
# create dataset

features=torch.rand(10,5)

# Create a model

model=Model(features.shape[1])

# Call model for forwrd pass

model(features)

tensor([[0.6061],
        [0.5928],
        [0.5955],
        [0.5990],
        [0.5997],
        [0.5376],
        [0.6290],
        [0.5855],
        [0.6149],
        [0.6031]], grad_fn=<SigmoidBackward0>)

In [18]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.0786,  0.0087, -0.0991, -0.2831,  0.2683]], requires_grad=True)

In [19]:
# show bias
model.linear.bias

Parameter containing:
tensor([0.3865], requires_grad=True)

In [20]:
! pip install torchinfo

In [21]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Neural Network with hidden layer

*5 inputs,1 hidden layer*

In [25]:
# Create model class

import torch 
import torch.nn as nn


class Model(nn.Module):

    def __init__(self,num_faetures):

        super().__init__()
        self.linear1=nn.Linear(num_faetures,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):

        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        

        return out
    

In [26]:
# create dataset

features=torch.rand(10,5)

# Create a model

model=Model(features.shape[1])

# Call model for forwrd pass

model(features)

tensor([[0.3518],
        [0.3517],
        [0.3417],
        [0.3370],
        [0.3303],
        [0.3974],
        [0.3935],
        [0.3518],
        [0.4091],
        [0.3951]], grad_fn=<SigmoidBackward0>)

In [27]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[ 0.1846,  0.3864,  0.4268, -0.2516, -0.1872],
        [ 0.2098,  0.2216, -0.2210,  0.3020, -0.4386],
        [-0.3294,  0.4285,  0.3678, -0.3580, -0.4442]], requires_grad=True)

In [28]:
model.linear2.weight

Parameter containing:
tensor([[-0.4750, -0.3867,  0.4824]], requires_grad=True)

In [29]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using Sequential Containers

In [ ]:
# Create model class

import torch 
import torch.nn as nn


class Model(nn.Module):

    def __init__(self,num_faetures):

        super().__init__()
        self.network=nn.Sequential(nn.Linear(num_faetures,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid())

    def forward(self,features):

        out=self.network(features)
        
        return out
    