In [36]:
from torch_setup import device


In [37]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder


In [38]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [80]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [81]:
df.shape

(569, 31)

In [82]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

KeyError: "['id', 'Unnamed: 32'] not found in axis"

In [83]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

#### Train test split

In [84]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=.2)

### Scaling

In [85]:
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [86]:
X_train


array([[ 1.08484284,  0.36428061,  1.34339149, ...,  1.27051502,
         0.5972054 ,  2.11416077],
       [ 0.86816989, -0.69657066,  1.000787  , ...,  2.16462073,
         2.00736754,  1.29998719],
       [-1.13253749,  0.4239822 , -1.15313484, ..., -1.33261424,
        -0.9417779 , -0.18134012],
       ...,
       [-0.29679896,  1.30802493, -0.36106588, ..., -0.82269935,
        -1.01563535, -1.21809352],
       [-0.0548006 , -0.57487128, -0.02050069, ...,  0.79752395,
         1.25848728,  1.29998719],
       [-1.2518483 , -0.59553721, -1.21635353, ..., -0.48718084,
         0.14547258,  0.85189886]])

In [87]:
y_train

400    M
25     M
425    B
394    B
294    B
      ..
333    B
268    B
458    B
215    M
341    B
Name: diagnosis, Length: 455, dtype: object

###  Label encoding

In [88]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [89]:
y_train

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,

In [90]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [91]:
X_train_tensor.shape


torch.Size([455, 30])

In [92]:
X_test_tensor.shape

torch.Size([114, 30])

In [93]:
y_train_tensor.shape

torch.Size([455])

### Defining model

In [94]:
class SimpleNN():

    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)


    def forward(self,X):
        z=torch.matmul(X, self.weights) + self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss


### Parameters

In [95]:
learning_rate=.1
epochs=25


### Training pipeline

In [96]:
# Create model
model=SimpleNN(X_train_tensor)

# define loop

for epoch in range(epochs):

    # forward pass
    y_pred=model.forward(X_train_tensor)
    
    
    # loss calculation
    loss=model.loss_function(y_pred,y_train_tensor)
    
    

    # backward pass
    loss.backward()


    # update parameters
    with torch.no_grad():
      model.weights -= learning_rate * model.weights.grad
      model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

     # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.7074992442455033
Epoch: 2, Loss: 3.5795498819629774
Epoch: 3, Loss: 3.4449059941001505
Epoch: 4, Loss: 3.3077362002004316
Epoch: 5, Loss: 3.166037171587347
Epoch: 6, Loss: 3.0169388136288355
Epoch: 7, Loss: 2.865077842624522
Epoch: 8, Loss: 2.7075316471134094
Epoch: 9, Loss: 2.5389829016103076
Epoch: 10, Loss: 2.364367293397195
Epoch: 11, Loss: 2.189973625507834
Epoch: 12, Loss: 2.0184760190850417
Epoch: 13, Loss: 1.8510990337358748
Epoch: 14, Loss: 1.6887147941698202
Epoch: 15, Loss: 1.531096471442843
Epoch: 16, Loss: 1.3801603336688526
Epoch: 17, Loss: 1.2414943674744372
Epoch: 18, Loss: 1.1208098613333428
Epoch: 19, Loss: 1.0200098770912285
Epoch: 20, Loss: 0.9397955171847617
Epoch: 21, Loss: 0.8792689938457003
Epoch: 22, Loss: 0.8359395080263679
Epoch: 23, Loss: 0.8062028775975874
Epoch: 24, Loss: 0.7861814591946322
Epoch: 25, Loss: 0.7725251363727623


In [97]:

model.bias

tensor([-0.1191], dtype=torch.float64, requires_grad=True)

In [98]:
model.bias

tensor([-0.1191], dtype=torch.float64, requires_grad=True)

### Evaluation

In [99]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.632964015007019
