# Simple neural network

In [16]:
# Create model class

import torch 
import torch.nn as nn


class Model(nn.Module):

    def __init__(self,num_faetures):

        super().__init__()
        self.linear=nn.Linear(num_faetures,1)
        self.sigmoid=nn.Sigmoid()
    

    def forward(self,features):

        out=self.linear(features)
        out=self.sigmoid(out)

        return out
    
    



In [17]:
# create dataset

features=torch.rand(10,5)

# Create a model

model=Model(features.shape[1])

# Call model for forwrd pass

model(features)

tensor([[0.6061],
        [0.5928],
        [0.5955],
        [0.5990],
        [0.5997],
        [0.5376],
        [0.6290],
        [0.5855],
        [0.6149],
        [0.6031]], grad_fn=<SigmoidBackward0>)

In [18]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.0786,  0.0087, -0.0991, -0.2831,  0.2683]], requires_grad=True)

In [19]:
# show bias
model.linear.bias

Parameter containing:
tensor([0.3865], requires_grad=True)

In [20]:
! pip install torchinfo

In [21]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Neural Network with hidden layer

*5 inputs,1 hidden layer*

In [33]:
# Create model class

import torch 
import torch.nn as nn


class Model(nn.Module):

    def __init__(self,num_faetures):

        super().__init__()
        self.linear1=nn.Linear(num_faetures,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):

        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        

        return out
    

In [34]:
# create dataset

features=torch.rand(10,5)

# Create a model

model=Model(features.shape[1])

# Call model for forwrd pass

model(features)

tensor([[0.5765],
        [0.5418],
        [0.5764],
        [0.5588],
        [0.5655],
        [0.5328],
        [0.5511],
        [0.5786],
        [0.4971],
        [0.5379]], grad_fn=<SigmoidBackward0>)

In [35]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[ 0.4400, -0.0555, -0.4140, -0.0405,  0.2976],
        [-0.2443,  0.2847,  0.3152, -0.4202, -0.3024],
        [-0.1403,  0.0405,  0.3558, -0.3877, -0.2283]], requires_grad=True)

In [36]:
model.linear1.bias

Parameter containing:
tensor([ 0.3168, -0.3813, -0.1118], requires_grad=True)

In [28]:
model.linear2.weight

Parameter containing:
tensor([[-0.4750, -0.3867,  0.4824]], requires_grad=True)

In [37]:
model.linear2.bias

Parameter containing:
tensor([0.3957], requires_grad=True)

In [29]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using Sequential Containers

In [30]:
# Create model class

import torch 
import torch.nn as nn


class Model(nn.Module):

    def __init__(self,num_faetures):

        super().__init__()
        self.network=nn.Sequential(nn.Linear(num_faetures,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid())

    def forward(self,features):

        out=self.network(features)
        
        return out
    

In [31]:
# create dataset

features=torch.rand(10,5)

# Create a model

model=Model(features.shape[1])

# Call model for forwrd pass

model(features)

tensor([[0.5712],
        [0.5502],
        [0.5652],
        [0.5551],
        [0.5604],
        [0.5866],
        [0.5507],
        [0.5883],
        [0.5789],
        [0.5900]], grad_fn=<SigmoidBackward0>)