In [1]:
from torch_setup import device


Using device: cuda


In [2]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder


In [3]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [4]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [7]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

#### Train test split

In [8]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=.2)

### Scaling

In [9]:
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [10]:
X_train


array([[-0.10432035, -0.7163373 , -0.17285623, ..., -0.93046278,
        -0.87244893, -0.68668945],
       [-0.71503504, -0.03509716, -0.75219167, ..., -0.90231868,
         0.99075875, -0.76930365],
       [-1.28719309, -0.18074161, -1.27641064, ..., -0.777724  ,
         0.47237297,  0.06536625],
       ...,
       [ 0.41914939, -1.87444554,  0.41015365, ...,  0.43323283,
        -0.54949293, -0.11745098],
       [ 2.8169785 ,  0.22095517,  2.99858685, ...,  1.64418966,
         0.55186983, -0.20912609],
       [-0.5124016 , -0.99118246, -0.57745202, ..., -1.15926668,
         0.02023457, -0.86257775]])

In [11]:
y_train

357    B
310    B
470    B
371    B
464    B
      ..
153    B
478    B
484    B
122    M
241    B
Name: diagnosis, Length: 455, dtype: object

###  Label encoding

In [12]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [13]:
y_train

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [14]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape


torch.Size([455, 30])

In [16]:
X_test_tensor.shape

torch.Size([114, 30])

In [17]:
y_train_tensor.shape

torch.Size([455])

### Defining model

In [18]:
class SimpleNN():

    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)


    def forward(self,X):
        z=torch.matmul(X, self.weights) + self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss


### Parameters

In [19]:
learning_rate=.1
epochs=25


### Training pipeline

In [20]:
# Create model
model=SimpleNN(X_train_tensor)

# define loop

for epoch in range(epochs):

    # forward pass
    y_pred=model.forward(X_train_tensor)
    
    
    # loss calculation
    loss=model.loss_function(y_pred,y_train_tensor)
    
    

    # backward pass
    loss.backward()


    # update parameters
    with torch.no_grad():
      model.weights -= learning_rate * model.weights.grad
      model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

     # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.392119012080906
Epoch: 2, Loss: 3.2594287280822614
Epoch: 3, Loss: 3.1229992991865596
Epoch: 4, Loss: 2.9768754796055266
Epoch: 5, Loss: 2.825108142632222
Epoch: 6, Loss: 2.6745456594230705
Epoch: 7, Loss: 2.523466591354607
Epoch: 8, Loss: 2.368826432544831
Epoch: 9, Loss: 2.2108111613091253
Epoch: 10, Loss: 2.051389429315214
Epoch: 11, Loss: 1.8930010212113477
Epoch: 12, Loss: 1.7389626598677572
Epoch: 13, Loss: 1.5941916723577667
Epoch: 14, Loss: 1.4556723940465859
Epoch: 15, Loss: 1.3314233891602418
Epoch: 16, Loss: 1.2228093383906438
Epoch: 17, Loss: 1.1305184462275906
Epoch: 18, Loss: 1.0543296935165916
Epoch: 19, Loss: 0.9931268198414572
Epoch: 20, Loss: 0.9450989748041663
Epoch: 21, Loss: 0.90802793397775
Epoch: 22, Loss: 0.8796036807762616
Epoch: 23, Loss: 0.8576994845005518
Epoch: 24, Loss: 0.8405462233597988
Epoch: 25, Loss: 0.8267903513997362


In [21]:

model.bias

tensor([-0.1184], dtype=torch.float64, requires_grad=True)

In [22]:
model.bias

tensor([-0.1184], dtype=torch.float64, requires_grad=True)

### Evaluation

In [23]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6446598768234253
